# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    environment:
      MYSQL_USER: cmargueiz
      MYSQL_PASSWORD: Contabilidad23
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: Contabilidad
    ports:
      - 3308:3306
    volumes:
      - ./db_data:/var/lib/mysql\
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_ARBITRARY=1
